apiVersion: v1
kind: Service
metadata:
  name: binance-watchlist-agent
  namespace: function
  labels:
    app: binance-watchlist-agent
spec:
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
  selector:
    app: binance-watchlist-agent
